<?php
declare(strict_types=1);

/**
 * Dump current MariaDB rows into database/seeds.sql.
 * Usage: C:\xampp\php\php.exe scripts/export-seeds.php
 *
 * Does not write plaintext passwords. User rows include Argon2id hashes only.
 */

if (PHP_SAPI !== 'cli') {
    http_response_code(403);
    exit('Forbidden');
}

require_once dirname(__DIR__) . '/config/db.php';

$pdo = db();
$outPath = dirname(__DIR__) . DIRECTORY_SEPARATOR . 'database' . DIRECTORY_SEPARATOR . 'seeds.sql';

$tables = [
    'users' => [
        'id', 'name', 'email', 'password_hash', 'role', 'created_at', 'updated_at', 'last_login_at',
    ],
    'products' => [
        'id', 'name', 'slug', 'category', 'description', 'price_php', 'image_path', 'stock', 'badge', 'is_active', 'created_at', 'updated_at',
    ],
    'orders' => [
        'id', 'public_code', 'user_id', 'fulfillment', 'payment_method', 'status',
        'date_needed', 'time_needed', 'customer_name', 'customer_contact',
        'delivery_receiver', 'delivery_contact', 'delivery_location',
        'total_php', 'created_at', 'updated_at',
    ],
    'order_items' => [
        'id', 'order_id', 'product_id', 'product_name_snapshot',
        'unit_price_php_snapshot', 'image_path_snapshot', 'qty',
    ],
];

$duplicateUpdates = [
    'users' => ['name', 'role'],
    'products' => ['name', 'category', 'description', 'price_php', 'image_path', 'badge', 'is_active'],
    'orders' => [
        'user_id', 'fulfillment', 'payment_method', 'status', 'date_needed', 'time_needed',
        'customer_name', 'customer_contact', 'delivery_receiver', 'delivery_contact',
        'delivery_location', 'total_php',
    ],
    'order_items' => [
        'order_id', 'product_id', 'product_name_snapshot',
        'unit_price_php_snapshot', 'image_path_snapshot', 'qty',
    ],
];

function sql_quote(PDO $pdo, mixed $value): string
{
    if ($value === null) {
        return 'NULL';
    }
    if (is_int($value)) {
        return (string) $value;
    }

    $quoted = $pdo->quote((string) $value);
    if ($quoted === false) {
        throw new RuntimeException('Failed to quote a seed value.');
    }

    return $quoted;
}

$chunks = [];
$chunks[] = "-- KDesigns seed data — utf8mb4";
$chunks[] = "-- Generated by scripts/export-seeds.php. Re-run that script to refresh from live MariaDB.";
$chunks[] = "-- No plaintext passwords. users.password_hash is Argon2id.";
$chunks[] = "-- Product stock is inserted for empty databases and is NOT overwritten on re-run.";
$chunks[] = "";
$chunks[] = "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;";
$chunks[] = "SET FOREIGN_KEY_CHECKS = 0;";
$chunks[] = "";

foreach ($tables as $table => $columns) {
    $colList = '`' . implode('`, `', $columns) . '`';
    $stmt = $pdo->query('SELECT ' . $colList . ' FROM `' . $table . '` ORDER BY `id` ASC');
    $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);

    $chunks[] = '-- ---------------------------------------------------------------------------';
    $chunks[] = '-- ' . $table . ' (' . count($rows) . ' rows)';
    $chunks[] = '-- ---------------------------------------------------------------------------';

    if ($rows === []) {
        $chunks[] = '-- (no rows)';
        $chunks[] = '';
        continue;
    }

    $updates = $duplicateUpdates[$table];
    $updateSql = implode(', ', array_map(
        static fn (string $col): string => '`' . $col . '` = VALUES(`' . $col . '`)',
        $updates
    ));

    foreach ($rows as $row) {
        $values = [];
        foreach ($columns as $col) {
            $raw = $row[$col];
            if ($raw === null) {
                $values[] = 'NULL';
                continue;
            }
            if (in_array($col, ['id', 'user_id', 'order_id', 'product_id', 'price_php', 'stock', 'is_active', 'total_php', 'qty', 'unit_price_php_snapshot'], true)) {
                $values[] = (string) (int) $raw;
                continue;
            }
            $values[] = sql_quote($pdo, $raw);
        }

        $chunks[] = 'INSERT INTO `' . $table . '` (' . $colList . ') VALUES (' . implode(', ', $values) . ')';
        $chunks[] = 'ON DUPLICATE KEY UPDATE ' . $updateSql . ';';
    }

    $chunks[] = '';
}

$chunks[] = 'SET FOREIGN_KEY_CHECKS = 1;';
$chunks[] = '';

$sql = implode("\n", $chunks) . "\n";
if (file_put_contents($outPath, $sql) === false) {
    throw new RuntimeException('Failed to write database/seeds.sql.');
}

echo 'OK wrote ' . $outPath . PHP_EOL;
foreach ($tables as $table => $columns) {
    $count = (int) $pdo->query('SELECT COUNT(*) FROM `' . $table . '`')->fetchColumn();
    echo 'OK ' . $table . ' rows=' . $count . PHP_EOL;
}
echo 'OK export complete' . PHP_EOL;
